# Generated by Django 3.2.5 on 2021-12-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poolphase',
            name='name',
            field=models.CharField(choices=[('Small-Pool-Phase', 'Small-Pool-Phase'), ('Large-Pool-Phase', 'Large-Pool-Phase')], max_length=50),
        ),
    ]
