# Generated by Django 3.2.5 on 2021-12-12 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='_elimination_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EL_players', to='chessclubs.eliminationrounds'),
        ),
    ]
