# Generated by Django 3.2.5 on 2021-12-03 18:35

import chessclubs.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(96)])),
                ('deadline', models.DateTimeField(validators=[chessclubs.models.validate_tournament_deadline])),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_tournaments', to='chessclubs.club')),
                ('co_organisers', models.ManyToManyField(related_name='co_organised_tournaments', to=settings.AUTH_USER_MODEL)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organised_tournaments', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
