# Generated by Django 3.2.5 on 2021-12-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('user', 'tournament')},
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['user', 'tournament'], name='chessclubs__user_id_316feb_idx'),
        ),
    ]
