# Generated by Django 3.2.5 on 2021-12-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='tournament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='chessclubs.tournament'),
        ),
    ]
