# Generated by Django 3.2.5 on 2021-12-04 11:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chessclubs', '0002_tournament'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'permissions': [('play_matches', 'Can play matches'), ('enter_match_results', 'Can enter match results'), ('see_tournament_private_info', 'Can see tournament private info')]},
        ),
        migrations.AlterField(
            model_name='tournament',
            name='capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(96)]),
        ),
        migrations.CreateModel(
            name='TournamentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_permission', to='auth.permission')),
                ('groups', models.ManyToManyField(related_name='tournament_permissions', to='auth.Group')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessclubs.tournament')),
                ('users', models.ManyToManyField(related_name='user_tournament_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='tournamentpermission',
            index=models.Index(fields=['tournament', 'base_permission'], name='chessclubs__tournam_556660_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentpermission',
            unique_together={('tournament', 'base_permission')},
        ),
    ]
