# Generated by Django 3.2.5 on 2021-12-05 23:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0002_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(96)]),
        ),
    ]
