# Generated by Django 3.2.5 on 2021-12-13 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0002_alter_poolphase_name'),
        ('chessclubs', '0002_auto_20211213_0148'),
    ]

    operations = [
    ]
