# Generated by Django 3.2.5 on 2021-12-12 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0002_alter_player__elimination_round'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmallPoolPhase',
        ),
    ]
