# Generated by Django 3.2.5 on 2021-12-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0002_auto_20211210_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-_points']},
        ),
        migrations.RenameField(
            model_name='player',
            old_name='points',
            new_name='_points',
        ),
    ]
