# Generated by Django 3.2.5 on 2021-12-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0003_merge_20211213_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='_encountered_players',
            field=models.ManyToManyField(related_name='_chessclubs_player__encountered_players_+', to='chessclubs.Player'),
        ),
    ]
