# Generated by Django 3.2.5 on 2021-12-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0003_alter_club_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'permissions': [('play_matches', 'Can play matches'), ('enter_match_results', 'Can enter match results'), ('see_tournament_private_info', 'Can see tournament private info'), ('withdraw', 'Can withdraw'), ('add_co_organiser', 'Can add co-organiser')]},
        ),
    ]
