# Generated by Django 3.2.5 on 2021-12-11 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0003_alter_player_tournament'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'permissions': [('play_matches', 'Can play matches'), ('enter_match_results', 'Can enter match results'), ('see_tournament_private_info', 'Can see tournament private info'), ('withdraw', 'Can withdraw')]},
        ),
    ]
