# Generated by Django 3.2.5 on 2021-12-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0003_delete_smallpoolphase'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='all_matches_played',
            field=models.BooleanField(default=False),
        ),
    ]
