# Generated by Django 3.2.5 on 2021-12-10 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0003_auto_20211210_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smallpool',
            old_name='_all_matches_played',
            new_name='all_matches_played',
        ),
    ]
