# Generated by Django 3.2.5 on 2021-11-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
