# Generated by Django 3.2.5 on 2021-12-11 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0004_alter_tournament_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eliminationrounds',
            name='_players',
        ),
        migrations.RemoveField(
            model_name='smallpool',
            name='_players',
        ),
        migrations.RemoveField(
            model_name='smallpoolphase',
            name='_players',
        ),
        migrations.RemoveField(
            model_name='smallpoolphase',
            name='_qualified_players',
        ),
        migrations.AddField(
            model_name='player',
            name='_elimination_round',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EL_players', to='chessclubs.eliminationrounds'),
        ),
        migrations.AddField(
            model_name='player',
            name='_small_pool',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='small_pool_players', to='chessclubs.smallpool'),
        ),
        migrations.AddField(
            model_name='player',
            name='_small_pool_phase',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SPP_players', to='chessclubs.smallpoolphase'),
        ),
        migrations.AddField(
            model_name='player',
            name='_won_small_pool_phase',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SPP_qualified_players', to='chessclubs.smallpoolphase'),
        ),
        migrations.AddField(
            model_name='smallpoolphase',
            name='_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eliminationrounds',
            name='_winner',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_elimination_rounds', to='chessclubs.player'),
        ),
    ]
