# Generated by Django 3.2.5 on 2021-12-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0004_player__encountered_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='_schedule_published',
            field=models.BooleanField(default=False),
        ),
    ]
