# Generated by Django 3.2.5 on 2021-12-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0004_rename__all_matches_played_smallpool_all_matches_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='_finished',
            field=models.BooleanField(default=False),
        ),
    ]
