# Generated by Django 3.2.5 on 2021-12-16 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0004_alter_tournament_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'permissions': [('play_matches', 'Can play matches'), ('enter_match_results', 'Can enter match results'), ('see_tournament_private_info', 'Can see tournament private info'), ('withdraw', 'Can withdraw'), ('add_co_organiser', 'Can add co-organiser'), ('start_tournament', 'Can start tournament'), ('publish_schedule', 'Can publish schedule')]},
        ),
    ]
