# Generated by Django 3.2.5 on 2021-12-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0003_alter_tournament_capacity'),
        ('chessclubs', '0005_alter_club_options'),
    ]

    operations = [
    ]
