# Generated by Django 3.2.5 on 2021-11-19 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0005_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
