# Generated by Django 3.2.5 on 2021-11-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0006_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
