# Generated by Django 3.2.5 on 2021-12-07 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0007_auto_20211206_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='capacity',
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_capacity',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(96, 'The max capacity needs to be less than 96.'), django.core.validators.MinValueValidator(2, 'The max capacity needs to be at least 2.')]),
        ),
    ]
