# Generated by Django 3.2.5 on 2021-11-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0008_alter_user_options'),
        ('chessclubs', '0008_alter_user_personal_statement'),
    ]

    operations = [
    ]
