# Generated by Django 3.2.5 on 2021-11-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0009_merge_20211122_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('access_members_list', 'Can access the list of members'), ('show_public_info', "Can access a member's public info"), ('show_private_info', "Can access a member's private info"), ('promote', 'Can promote members'), ('demote', 'Can demote officers'), ('transfer_ownership', 'Can transfer ownership to an officer'), ('manage_applications', 'Can manage applications'), ('access_club_info', "Can access a club's public info"), ('access_club_owner_public_info', 'Can access a club owner public info')]},
        ),
    ]
