# Generated by Django 3.2.5 on 2021-12-08 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0009_eliminationrounds_groupstage_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='_current_phase',
            field=models.CharField(choices=[('Elimination-Rounds', 'Elimination-Rounds'), ('Small_Group_Phase', 'Small_Group_Phase'), ('Large-Group-Phase', 'Large-Group-Phase')], default='Elimination-Rounds', max_length=50),
        ),
        migrations.AlterField(
            model_name='eliminationrounds',
            name='_small_group_stage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_elimination_round', to='chessclubs.groupstage'),
        ),
        migrations.AlterField(
            model_name='eliminationrounds',
            name='_tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elimination_round', to='chessclubs.tournament'),
        ),
    ]
