# Generated by Django 3.2.5 on 2021-12-08 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0010_auto_20211208_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliminationrounds',
            name='_small_group_stage',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='own_elimination_round', to='chessclubs.groupstage'),
        ),
        migrations.AlterField(
            model_name='match',
            name='_player2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
