
# Generated by Django 3.2.5 on 2021-11-27 13:59


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0011_alter_user_options'),
        ('chessclubs', '0011_club'),
    ]

    operations = [
    ]
