# Generated by Django 3.2.5 on 2021-11-26 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chessclubs', '0012_merge_0011_alter_user_options_0011_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='applicants_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='auth.group'),
        ),
        migrations.AddField(
            model_name='club',
            name='authenticated_non_member_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='authenticated_non_members', to='auth.group'),
        ),
        migrations.AddField(
            model_name='club',
            name='denied_applicants_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='denied_applicants', to='auth.group'),
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(related_name='clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='members_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='auth.group'),
        ),
        migrations.AddField(
            model_name='club',
            name='officers_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
