# Generated by Django 3.2.5 on 2021-12-08 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0012_auto_20211208_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eliminationrounds',
            old_name='_phase',
            new_name='phase',
        ),
        migrations.RenameField(
            model_name='eliminationrounds',
            old_name='_small_group_stage',
            new_name='small_group_stage',
        ),
    ]
