# Generated by Django 3.2.5 on 2021-12-08 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0013_auto_20211208_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='EliminationRoundMatch',
            fields=[
                ('match_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chessclubs.match')),
            ],
            bases=('chessclubs.match',),
        ),
        migrations.RemoveField(
            model_name='eliminationrounds',
            name='small_group_stage',
        ),
        migrations.AlterField(
            model_name='eliminationrounds',
            name='_tournament',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elimination_round', to='chessclubs.tournament'),
        ),
        migrations.AlterField(
            model_name='eliminationrounds',
            name='phase',
            field=models.CharField(choices=[('Final', 'Final'), ('Semi-Final', 'Semi-Final'), ('Quarter-Final', 'Quarter_Final'), ('Eighth-Final', 'Eighth-Final')], default='Eighth-Final', max_length=50),
        ),
        migrations.DeleteModel(
            name='GroupStage',
        ),
        migrations.AddField(
            model_name='eliminationroundmatch',
            name='elimination_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='chessclubs.eliminationrounds'),
        ),
    ]
