# Generated by Django 3.2.5 on 2021-11-27 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('chessclubs', '0014_auto_20211126_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'permissions': [('access_members_list', 'Can access the list of members'), ('show_public_info', "Can access a member's public info"), ('show_private_info', "Can access a member's private info"), ('promote', 'Can promote members'), ('demote', 'Can demote officers'), ('transfer_ownership', 'Can transfer ownership to an officer'), ('manage_applications', 'Can manage applications'), ('access_club_info', "Can access a club's public info"), ('access_club_owner_public_info', 'Can access a club owner public info'), ('acknowledge_denial', 'Can acknowledge denial of application')]},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.CreateModel(
            name='ClubPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_permission', to='auth.permission')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chessclubs.club')),
                ('groups', models.ManyToManyField(related_name='club_permissions', to='auth.Group')),
                ('users', models.ManyToManyField(related_name='user_club_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='clubpermission',
            index=models.Index(fields=['club', 'base_permission'], name='chessclubs__club_id_da7704_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clubpermission',
            unique_together={('club', 'base_permission')},
        ),
    ]
