# Generated by Django 3.2.5 on 2021-11-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chessclubs', '0012_auto_20211125_2325'),
        ('chessclubs', '0015_auto_20211127_1055'),
    ]

    operations = [
    ]
